### ISSUE TITLE
Crash:  NSManagedObjectContext+MagicalSaves.m line 82

### ISSUE THREAD

**Issue by Spokane-Dude** [magicalpanda/MagicalRecord#860]
This is the stack trace (let me know if you need more info):

```
Thread : Crashed: com.apple.main-thread
0  libobjc.A.dylib                0x39623626 objc_msgSend
1  Foundation                     0x2f346d9d -[NSError dealloc]
2  libobjc.A.dylib                0x39628b6b objc_object::sidetable_release(bool)
3  libobjc.A.dylib                0x396290d7 (anonymous namespace)::AutoreleasePoolPage::pop(void*)
4  CoreFoundation                 0x2e957c19 _CFAutoreleasePoolPop
5  Foundation                     0x2f351637 -[NSAutoreleasePool drain]
6  CoreData                       0x2e798fb9 -[NSManagedObjectContext save:]
7  SalonBook                      0x0005b91f __70-[NSManagedObjectContext(MagicalSaves) MR_saveWithOptions:completion:]_block_invoke15 (NSManagedObjectContext+MagicalSaves.m:82)
8  CoreData                       0x2e7fc935 developerSubmittedBlockToNSManagedObjectContextPerform
9  libdispatch.dylib              0x39b0181f _dispatch_client_callout
10 libdispatch.dylib              0x39b0849f _dispatch_main_queue_callback_4CF$VARIANT$mp
11 CoreFoundation                 0x2e9ee8a1 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
12 CoreFoundation                 0x2e9ed175 __CFRunLoopRun
13 CoreFoundation                 0x2e957ebf CFRunLoopRunSpecific
14 CoreFoundation                 0x2e957ca3 CFRunLoopRunInMode
15 GraphicsServices               0x3385f663 GSEventRunModal
16 UIKit                          0x312a414d UIApplicationMain
17 SalonBook                      0x00041c47 main (main.m:15)
```

**Comment by jmkk** [comment]
This seemed to have been fixed in 8.0.0+, but now we're seeing this back in 8.1.3.
Anyone else getting crash reports with a similar stack trace in 8.1.3 now? Thanks!

**Comment by heatherSnepenger** [comment]
I'm similarly seeing this issue in 8.1.3

**Comment by sebdah** [comment]
We are seeing this as well for iOS 7.1.2

**Comment by Sipeso** [comment]
@sebdah When this is still an issue for you, please post more details: A stack-trace, the exact version of Magical Record you are using, did you migrate your core-data-model recently?
